#!/usr/bin/env bash

HELP=",clip $(git describe --always --tags)

copy and paste to/from the system clipboard

USAGE
  pass text on stdin to copy
  $ ,clip < text
  paste to stdout
  $ ,clip"

if test "$1" = "-h"; then
  echo "$HELP"
  exit 0
fi

if test -t 0; then
  # paste
  xclip -o -selection clipboard
else
  # copy
  xclip -i -selection clipboard < /dev/stdin
fi
