#!/usr/bin/env bash

VERSION=

HELP=",cut $VERSION

like cut but only for space-delimited word lists

USAGE
  $ ,cut <field> < wordlist"

if test $1 = "-h"; then
  echo "$HELP"
  exit 0
fi

FIELD=$1

if test -z $FIELD; then
  echo ",cut error: missing field arg" >&2
  exit 1
fi

while read line; do
  COUNT=$(wc -w <<< "$line")
  if test $FIELD -gt $COUNT; then
    echo ",cut error: field arg is out of bounds" >&2
    exit 1
  fi
  tr -s ' ' <<< "$line" | cut -d " " -f $FIELD
done < /dev/stdin
